working with graphs: we have a module named scipy.sparse.csgraph

djacency Matrix: nxn matrix where n is the number of element in the graph.

Connected Component:

In [21]:
import numpy as np
from scipy.sparse.csgraph import connected_components ,dijkstra, floyd_warshall, bellman_ford, depth_first_order, breadth_first_order
from scipy.sparse import csr_matrix

In [22]:
arr = np.array(
    [
        [0, 1, 0, 1],
        [1, 0, 1, 1],
        [0, 1, 0, 1],
        [1, 1, 1, 0]
    ]
)
arr

array([[0, 1, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 0]])

In [23]:
newArr = csr_matrix(arr)
print(newArr)

  (0, 1)	1
  (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (1, 3)	1
  (2, 1)	1
  (2, 3)	1
  (3, 0)	1
  (3, 1)	1
  (3, 2)	1


In [24]:
connected_components(newArr)

(1, array([0, 0, 0, 0]))

Dijkstra method: for finding the shortest path in a graph from one element to another

it take 3 arg: return_predecessors, indices, limit

here we will find te shortest path from element 1 to 2:

In [25]:
dijkstra( 
    newArr,
    return_predecessors = True,
    indices=0
)

(array([0., 1., 2., 1.]), array([-9999,     0,     1,     0]))

In [26]:
dijkstra( newArr,indices=0)

array([0., 1., 2., 1.])

Floyd Warshall() method: it is for finding the shortest path between all the pairs of elements.

In [27]:
bellman_ford( newArr, return_predecessors=True)

(array([[0., 1., 2., 1.],
        [1., 0., 1., 1.],
        [2., 1., 0., 1.],
        [1., 1., 1., 0.]]),
 array([[-9999,     0,     1,     0],
        [    1, -9999,     1,     1],
        [    3,     2, -9999,     2],
        [    3,     3,     3, -9999]]))

 Bellman_ford() method: it is for finding the shortest path between all the pairs of elements but this method can handle negative weight as well:

In [28]:
bellman_ford(
    newArr,
    return_predecessors=True,
    indices = 0
)

(array([0., 1., 2., 1.]), array([-9999,     0,     1,     0]))

Depth first order: it returns a depth first traversal froma node: it has 2 argu: the graph, starting element

In [29]:
depth_first_order( newArr, 1)

(array([1, 0, 3, 2]), array([    1, -9999,     3,     0]))

breadth_first_order() method: it returns the breadth from a node:it has 2 argu: the graph, starting element

In [30]:
breadth_first_order( newArr, 1)

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))